import { cn } from "@/lib/utils";
import {
  AtSign,
  FileUser,
  Github,
  Languages,
  Linkedin,
  MapPin,
  Monitor,
  Moon,
  Sun,
} from "lucide-react";
import type { Metadata } from "next";
import localFont from "next/font/local";
import Link from "next/link";
import "./globals.css";
import { NavController } from "./NavController";
import { BackgroundGrid } from "./BackgroundGrid";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const GRID_ITEM_CLASSES = "bg-grid-item-background rounded-lg px-7 py-5";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="flex h-screen items-center justify-center">
          <div className="grid h-[85vh] w-[85vw] max-w-5xl grid-cols-11 grid-rows-[14] gap-5">
            {children}
            <NavBar />
            <div
              className={cn(
                GRID_ITEM_CLASSES,
                "col-span-4 row-span-3 row-start-11 flex flex-row items-center justify-evenly py-3",
              )}
            >
              <span className="rounded-lg bg-background px-5 py-2 text-text-primary">
                English
              </span>
              <div className="rounded-lg bg-text-cta px-3 py-1">
                <Languages className="" />
              </div>
              <span className="rounded-lg px-5 py-2 text-text-secondary">
                Finnish
              </span>
            </div>
            <Link
              href="mailto:contact@axu5.com"
              className={cn(
                GRID_ITEM_CLASSES,
                "group col-span-4 row-span-1 row-start-[14] flex flex-row items-center justify-between text-xl text-text-primary hover:underline",
              )}
            >
              <AtSign className="group-hover:motion-preset-spin motion-duration-2000 text-text-cta" />{" "}
              contact@axu5.com
            </Link>
            <Link
              href="https://linkedin.com/in/aleksanteri-aho"
              target="_blank"
              className={cn(
                GRID_ITEM_CLASSES,
                "group col-span-2 row-span-4 flex flex-row items-center justify-center bg-linked-in",
              )}
            >
              <Linkedin className="text-text-secondary group-hover:text-text-primary" />
            </Link>
            <Link
              href="https://github.com/axu5"
              target="_blank"
              className={cn(
                GRID_ITEM_CLASSES,
                "group col-span-2 row-span-4 flex flex-row items-center justify-center bg-github",
              )}
            >
              <Github className="text-text-secondary group-hover:text-text-primary" />
            </Link>
            <div
              className={cn(
                GRID_ITEM_CLASSES,
                "col-span-3 row-span-2 flex flex-row items-center justify-between text-xl text-text-primary",
              )}
            >
              <Monitor />
              <Sun />
              <Moon />
            </div>
            <div
              className={cn(
                GRID_ITEM_CLASSES,
                "col-span-3 row-span-2 flex flex-row items-center justify-between text-xl text-text-primary",
              )}
            >
              <MapPin className="text-text-cta" />
              Mikkeli, Finland
            </div>
          </div>
        </div>
        <BackgroundGrid />
      </body>
    </html>
  );
}

async function NavBar() {
  return (
    <nav
      className={cn(
        GRID_ITEM_CLASSES,
        "col-span-3 col-start-9 row-span-10 row-start-1 flex flex-col justify-between",
      )}
    >
      <NavController />
      <Link
        href="#"
        className="border-gradient-to-br flex flex-row items-center gap-x-4 rounded-lg border from-text-secondary via-text-cta to-text-cta px-5 py-3 text-text-primary hover:border-text-cta"
      >
        <FileUser className="h-4 w-4" />
        Request CV
      </Link>
    </nav>
  );
}
