import { cn } from "@/lib/utils";
import {
  AtSign,
  BookUser,
  BriefcaseBusiness,
  Code,
  FileUser,
  Github,
  GraduationCap,
  Home,
  Languages,
  Linkedin,
  MapPin,
  User,
} from "lucide-react";
import type { Metadata } from "next";
import localFont from "next/font/local";
import Link from "next/link";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const GRID_ITEM_CLASSES =
  "bg-grid-item-background rounded-lg p-5";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex justify-center items-center h-screen`}>
        <div className='grid grid-rows-[14] grid-cols-11 max-w-5xl gap-5'>
          {children}
          <NavBar />
          <div
            className={cn(
              GRID_ITEM_CLASSES,
              "flex flex-row row-span-3 col-span-4 row-start-11 justify-evenly items-center py-3"
            )}>
            <span className='text-text-primary rounded-lg bg-background px-5 py-2'>
              English
            </span>
            <div className='bg-text-cta px-3 py-1 rounded-lg'>
              <Languages className='' />
            </div>
            <span className='text-text-secondary rounded-lg px-5 py-2'>
              Finnish
            </span>
          </div>
          <div
            className={cn(
              GRID_ITEM_CLASSES,
              "flex flex-row justify-between row-span-1 col-span-4 row-start-[14] items-center text-text-primary text-xl"
            )}>
            <AtSign className='text-text-cta' /> contact@axu5.com
          </div>
          <Link
            href='https://linkedin.com/in/aleksanteri-aho'
            target='_blank'
            className={cn(
              GRID_ITEM_CLASSES,
              "flex flex-row justify-center items-center row-span-4 col-span-2 bg-linked-in group"
            )}>
            <Linkedin className='text-text-secondary group-hover:text-text-primary' />
          </Link>
          <Link
            href='https://github.com/axu5'
            target='_blank'
            className={cn(
              GRID_ITEM_CLASSES,
              "flex flex-row justify-center items-center row-span-4 col-span-2 bg-github group"
            )}>
            <Github className='text-text-secondary group-hover:text-text-primary' />
          </Link>
          <div
            className={cn(
              GRID_ITEM_CLASSES,
              "flex flex-row row-span-2 col-span-3 items-center justify-between text-text-primary text-xl"
            )}>
            <MapPin className='text-text-cta' />
            Mikkeli, Finland
          </div>
        </div>
      </body>
    </html>
  );
}

function NavBar() {
  return (
    <nav
      className={cn(
        GRID_ITEM_CLASSES,
        "col-span-3 row-span-12 flex flex-col justify-between row-start-1 col-start-9"
      )}>
      <div className='flex flex-col'>
        <Link
          href='/'
          className='flex flex-row py-3 px-5 font-black text-text-secondary gap-x-4'>
          <Home />
          Home
        </Link>
        <Link
          href='/'
          className='flex flex-row py-3 px-5 font-black text-text-secondary gap-x-4'>
          <User />
          About
        </Link>
        <Link
          href='/'
          className='flex flex-row py-3 px-5 font-black text-text-secondary gap-x-4'>
          <BriefcaseBusiness />
          Experience
        </Link>
        <Link
          href='/'
          className='flex flex-row py-3 px-5 font-black text-text-secondary gap-x-4'>
          <GraduationCap />
          Education
        </Link>
        <Link
          href='/'
          className='flex flex-row py-3 px-5 font-black text-text-secondary gap-x-4'>
          <Code />
          Projects
        </Link>
        <Link
          href='/'
          className='flex flex-row py-3 px-5 font-black text-text-secondary gap-x-4'>
          <BookUser />
          Contact
        </Link>
      </div>
      <Link
        href='#'
        className='py-3 flex flex-row gap-x-4 items-center px-5 border border-gradient-to-br rounded-lg text-text-primary from-text-secondary via-text-cta to-text-cta hover:border-text-cta'>
        <FileUser className='w-4 h-4' />
        Request CV
      </Link>
    </nav>
  );
}
